import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../src/styles/Home.module.css'
import {Footer} from '../src/components'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>

          <Link href={'/'}>
            <a>
              <div style={{width:'300px',height:'60px',border:'1px solid gray',textAlign:'center',padding:'20px 0',borderRadius:'10px'}}>
                <p style={{margin: 0}}>streamingHTML</p>
              </div>
            </a>
          </Link>
        </div>
      </main>

      <Footer/>
    </div>
  )
}

export default Home
